version: '3.8'

services:
  django-app:
    build: .
    container_name: django-hello-world
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    restart: unless-stopped